dependencies:
  - role: contabil
  - role: vendas
  - role: faturamento
  - role: logistica
  - role: ERP
  - role: PES01
  - role: PES00
  - role: LOG00
  - role: LOG01_W
  - role: workflow 
  - role: geolocation
  - role: apprise
  - role: FAT01
