services:
  Viasoft.Sales.Core:
    db:
      name: Viasoft_Sales_Core
      type: mssql
    version:
      unversioned: true

  Viasoft.Sales.CustomerPortfolio:
    db:
      name: Viasoft_Sales_CustomerPortfolio
      type: mssql

  Viasoft.Sales.Discount:
    db:
      name: Viasoft_Sales_Discount
      type: mssql
    version:
      unversioned: true

  Viasoft.Sales.PriceList:
    db:
      name: Viasoft_Sales_PriceList
      type: mssql
    version:
      unversioned: true

  Viasoft.Sales.Customers:
    db:
      name: Viasoft_Sales_Customers
      type: mssql
    version:
      unversioned: true

  Korp.Vendas.AutomatizacaoDeFrete:

  Viasoft.Sales.CommercialProposal.Gateway:
    db:
      name: Viasoft_Sales_CommercialProposal_Gateway
      type: postgres
    version:
      unversioned: true

  Viasoft.Vendas.Core:
    db:
      name: Viasoft_Vendas_Core
      type: postgres
  
  Korp.Legacy.Vendas:
    db:
      name: Korp_Legacy_Vendas
      type: mssql
    version:
      unversioned: true

  Korp.Vendas.CustoProduto:

  Korp.Sales.PriceControl:

  Korp.Vendas.ListaPreco:
