services:
  Korp.Legacy.ELT:
    db:
      name: Korp_Legacy_ELT
      type: postgres

  Viasoft.ERP.Core:
    db:
      name: Viasoft_ERP_Core
      type: mssql

  Viasoft.ERP.Sync:
    db:
      name: Viasoft_ERP_Sync
      type: postgres
    version:
      unversioned: true

  Viasoft.Legacy.Parametros:
    db:
      name: Viasoft_Legacy_Parametros
      type: mssql

  Viasoft.ERP.Activities:
    db:
      name: Viasoft_ERP_Activities
      type: postgres

  Viasoft.OrganizationalStructureManagement:
    db:
      name: Viasoft_OrganizationalStructureManagement
      type: postgres

  Viasoft.Customer.Portifolio:

  Viasoft.MessageBird:
    db:
      name: Viasoft_MessageBird
      type: mssql
