services:
  Viasoft.Faturamento.Core:
    db:
      name: Viasoft_Faturamento_Core
      type: postgres

  Viasoft.Billing.NFE:
    db:
      name: Viasoft_Billing_NFE
      type: mssql

  Korp.Legacy.Faturamento:
    db:
      name: Korp_Legacy_Faturamento
      type: mssql

  # Entrarão apenas em futuras versões
  #Viasoft.Faturamento.NotaFiscal.Core:
  #  db:
  #    name: Viasoft_Faturamento_NotaFiscal_Core
  #    type: mssql
#
  #Viasoft.Faturamento.SolicitacaoFaturamento.Gateway:
  #  db:
  #    name: Viasoft_Faturamento_SolicitacaoFaturamento_Gateway
  #    type: mssql
#
  #Viasoft.Faturamento.SolicitacaoFaturamento.Core:
  #  db:
  #    name: Viasoft_Faturamento_SolicitacaoFaturamento_Core
  #    type: mssql
#
  #Viasoft.Faturamento.SolicitacaoFaturamento.ReadModel:
  #  db:
  #    name: Viasoft_Faturamento_SolicitacaoFaturamento_ReadModel
  #    type: mssql
