services:
  Viasoft.Financeiro.Core:
    db:
      name: Viasoft_Financeiro_Core
      type: postgres

  Viasoft.FinancialAccounting.Installment:
    db:
      name: Viasoft_FinancialAccounting_Installment
      type: mssql

  Viasoft.FinancialAccounting.AccountsReceivable:
    db:
      name: Viasoft_FinancialAccounting_AccountsReceivable
      type: mssql

  Korp.Legacy.Financeiro:

  Korp.Financial.Situation:
