role_services:
  - Viasoft.Financeiro.Core:
    db:
      db_name: Viasoft_Financeiro_Core
      db_type: postgres

  - Viasoft.FinancialAccounting.Installment:
    db:
      db_name: Viasoft_FinancialAccounting_Installment
      db_type: mssql