- name: notificação de TenantManagement
  ansible.builtin.uri:
    url: "{{ gateway_url }}/TenantManagement/server-deploy/token/{{ token }}"
    method: "PUT"
    body_format: json
    body:
      status: completed
