services:

  Korp.Logistic.Tracking:

  Korp.Logistica.SaldoProdutos:

  Viasoft.Logistica.Inventario.Background:
    db:
      name: Viasoft_Logistica_Inventario_Background
      type: postgres
    version:
      unversioned: true

  Viasoft.Logistica.AjusteEstoque.Background:
    db:
      name: Viasoft_Logistica_AjusteEstoque_Background
      type: postgres
    version:
      unversioned: true

  Viasoft.Legacy.Logistica:
    db:
      name: Viasoft_Legacy_Logistica
      type: mssql

  # Viasoft.Logistica.SolicitacaoFaturamento.Gateway:
  #   db:
  #     name: Viasoft_Logistica_SolicitacaoFaturamento_Core
  #     type: mssql

  # Viasoft.Logistica.SolicitacaoFaturamento.Core:
  #   db:
  #     name: Viasoft_Logistica_SolicitacaoFaturamento_Core
  #     type: mssql

  # Viasoft.Logistica.SolicitacaoFaturamento.ReadModel:
  #   db:
  #     name: Viasoft_Logistica_SolicitacaoFaturamento_ReadModel
  #     type: mssql
