- name: adição de serviços de financeiro
  ansible.builtin.include_role:
    name: utils
    tasks_from: services/add_service-old
  vars:
    service_name: "{{ item }}"
    consul_kv: "{{ lookup('template', 'consul_kv/{{ item | lower }}.json.j2') }}"
  loop:
    - Viasoft.Financeiro.Core
    - Viasoft.FinancialAccounting.Installment
    - Viasoft.FinancialAccounting.Core
    - Korp.Financial.Situation

- name: criação de bancos de dados de financeiro
  ansible.builtin.include_role:
    name: utils
    tasks_from: "create_db/{{ item.db.db_type }}"
  vars:
    db_name: "{{ item.db.db_name }}"
  loop: "{{ role_services }}"

- name: configuração e transferência de arquivos de compose de financeiro - versionado
  ansible.builtin.template:
    dest: "{{ versioned_compose_dir_path }}/{{ item[:-3] | basename }}"
    src: "composes/{{ version_without_build }}/{{ item | basename }}"
    owner: "{{ linux_korp.user }}"
    group: root
    mode: '0644'
  loop:
    "{{ lookup('fileglob', 'templates/composes/{{ version_without_build }}/*', wantlist=True) | select('search','.yml.j2') }}"

- name: configuração e transferência de arquivos de compose de financeiro
  ansible.builtin.template:
    dest: "{{ compose_dir_path }}/{{ item[:-3] | basename }}"
    src: "composes/{{ item | basename }}"
    owner: "{{ linux_korp.user }}"
    group: root
    mode: '0644'
  loop:
    "{{ lookup('fileglob', 'templates/composes/*', wantlist=True) | select('search','.yml.j2') }}"

- name: criação e inicialização de financeiro-compose - versionado
  community.docker.docker_compose:
    project_src: "{{ versioned_compose_dir_path }}/"
    env_file: "{{ docker_env_file_path }}"
    files:
      - financeiro-compose.yml

- name: criação e inicialização de financeiro-compose
  community.docker.docker_compose:
    project_src: "{{ compose_dir_path }}/"
    env_file: "{{ docker_env_file_path }}"
    files:
      - financeiro-compose.yml
